apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-cd-poc
  name: argo-cd-poc
  namespace: argo-cd-poc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: argo-cd-poc
  template:
    metadata:
      labels:
        app: argo-cd-poc
    spec:
      containers:
      - image: kicbase/echo-server:1.0
        imagePullPolicy: IfNotPresent
        name: echo-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always

