apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-cd-poc
  name: argo-cd-poc
  namespace: argo-cd-poc
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31972
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: argo-cd-poc
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
